apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: spring-cloud-config
  namespace: spring-cloud
spec:
  replicas: 1
  template:
    metadata:
      labels:
        k8s-app: spring-cloud-config
    spec:
      containers:
      - name: spring-cloud-config
        image: 10.14.255.176/spring-cloud/config:latest
        #imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 8888
            protocol: TCP
