server:
  port: 8888
spring:
  cloud:
    config:
      server:
        git:
          uri: http://54.223.236.208/root/spring-cloud-config.git

eureka:
  client:
    serviceUrl:
      defaultZone: http://spring-cloud-eureka:8761/eureka/
  instance:
    preferIpAddress: true

