apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: spring-cloud-config-client
  namespace: spring-cloud
spec:
  replicas: 1
  template:
    metadata:
      labels:
        k8s-app: spring-cloud-config-client
    spec:
      containers:
      - name: spring-cloud-config-client
        image: 10.14.255.176/spring-cloud-test/config-client:latest
        #imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 8080
            protocol: TCP
